### ISSUE TITLE
How to use this module?

### ISSUE THREAD

**Issue by iamlvm** [Scypho/node-fuzzylite#2]
Thank for building this module, I am really interested in this work, but how can I use the module?

**Comment by eklockare** [comment]
Hi, here's an example.
Install in npm project:
`npm install fuzzylite --save`

code:
```
var Fuzzylite = require('fuzzylite');
var fuzzylite = new Fuzzylite('path/to/your/fuzzyrules.fcl');
var input1 = 0.1;
var input2 = 0.2;
function callback(error, output) {
    if(error) {
        return console.log('error: ' + error);
    }
    console.log('output is: ' + output);
}
fuzzylite.runController([
        input1,
        input2,
    ],
    callback
);
```

Check out the file `test-controller.fcl` for an example fcl file. The package only supports a single output but you can have multiple inputs.

**Comment by iamlvm** [comment]
Hi @ecksun , the module is able to run under your instruction. But it has a problem when I call **runController** in a loop as the following.
```javascript
var Fuzzylite = require('fuzzylite');
var fuzzylite = new Fuzzylite('dataMatlab/membership_function_pn.fis');
var input1 = 0.5;
var input2 = -0.5;
function callback(error, output) {
    if(error) {
        return console.log('error: ' + error);
    }
    console.log('output is: ' + output);
}
var i=0;
while(i<10){
    fuzzylite.runController([
        input1,
        input2,
    ],
    callback
    );
    i++;
    console.log("something");
}
```
Output:
something
something
something
something
something
something
something
something
something
something
output is: 0.165
output is: 0.165
output is: 0.165
output is: 0.165
output is: 0.165
output is: 0.165
output is: 0.165
output is: 0.165
output is: 0.165
output is: 0.165

> 

The **runController** is only called after the loop is finished.

**Comment by eklockare** [comment]
Hi @sotoremydocuments
This is as expected. The call to `runController` is asynchronous while the `console.log` statement is synchronous.

This means that the `runController` call will finish in the future and when it does, the callback will be called.
So everything you want to do with the result of `runController` needs to be done inside the callback.

This might provide some useful information:
https://blog.risingstack.com/node-hero-async-programming-in-node-js/
